### ISSUE TITLE
is this compliant with XML specification ?

### ISSUE THREAD

**Issue by AmauryVanEspen** [KostasSliazas/Europass-Maker-Offline#1]
Hi @KostasSliazas 
is the html rendered file compliant with the XML format ?
Thank you
Amaury

**Comment by KostasSliazas** [comment]
hello,

It just saves to html file and it's not generic format probably. They are
different formats comaring xml to html. Have a great days

When comparing *XML specification* and *HTML5*, it’s important to note that
they serve different purposes and are not directly comparable as "better"
or "worse." Here's an outline to clarify their roles and differences:
------------------------------
*1. XML Specification*

   - *Purpose*:
      - XML (eXtensible Markup Language) is a markup language designed to
      store and transport data in a platform-independent,
human-readable format.
      It is highly generic and doesn’t define any semantics, leaving
that to the
      application.
   - *Features*:
      - Customizable tags and structures.
      - Strictly follows rules for well-formedness (e.g., every tag must be
      properly nested and closed).
      - Can be validated against a schema (DTD or XSD) to ensure
      correctness.
      - Used in scenarios where structured data exchange is required (e.g.,
      web services, config files, etc.).
   - *Strengths*:
      - Universal data interchange format.
      - Clear separation of content and presentation.
      - Extensible, allowing users to define their own structure.
   - *Weaknesses*:
      - Verbose syntax, leading to large file sizes.
      - Requires more processing power and memory for parsing compared to
      lightweight alternatives (like JSON).

------------------------------
*2. HTML5*

   - *Purpose*:
      - HTML5 is a markup language used for structuring and presenting
      content on the web. It includes semantics for elements, multimedia
      integration, APIs, and interactivity features.
   - *Features*:
      - Built-in semantics: Tags like <article>, <header>, and <footer> for
      better content structuring.
      - Supports multimedia: <audio> and <video> for media embedding
      without plugins.
      - Interactive elements: Built-in support for APIs like <canvas>,
      Geolocation, and WebSockets.
      - Backward compatible with older HTML versions.
   - *Strengths*:
      - Optimized for web use, supporting modern browsers and devices.
      - Simplifies development with predefined elements and APIs.
      - Rich ecosystem for interactivity and multimedia.
   - *Weaknesses*:
      - Limited to web content; not designed for generic data interchange.
      - Less strict than XML, which can lead to inconsistent document
      structures.

------------------------------
*Key Comparisons*
*Aspect**XML Specification**HTML5*
*Primary Use* Data storage and interchange Web content presentation
*Structure* Fully customizable Predefined structure
*Strictness* Very strict (well-formed rules) Lenient (error-tolerant)
*Extensibility* Highly extensible Fixed set of tags and APIs
*Context* Platform-agnostic Web-specific
*Complexity* Verbose, complex Simplified for developers
------------------------------
*When to Use Each*

   -

   *XML* is ideal for:
   - Data exchange between systems (e.g., SOAP, configuration files).
      - Scenarios requiring strict data validation.
      - Custom markup requirements.
   -

   *HTML5* is ideal for:
   - Building web pages and apps.
      - Embedding multimedia and creating interactive UIs.
      - Using web-specific APIs and semantics.

If you're deciding based on a specific project or task, let me know your
use case, and I can provide a more tailored recommendation!

2024-11-20, tr, 11:49 Amaury Van Espen ***@***.***> rašė:

**Comment by KostasSliazas** [comment]
I have uploaded once pdf format to one webpage(don't remember name(some cv maker online)) and it could extract values(maybe not all) from .pdf when html was saved in *.pdf format in browser. (Probably by titles (semantic)). For example.
```
<section>
<h2 class="left">Address(es)</h2>
 <h3 class="righ">Address Address, Address Address (Address)</h3>
</section> 
```

**Comment by AmauryVanEspen** [comment]
Nice,
do you believe that we can build a XML format from the values ?

**Comment by KostasSliazas** [comment]
I have tested html source with online tools html > xml and it coverts probably best from tables. So maybe changing html structure to tables is most generic way. They read best from tables as I understand for converting. So it could be done by modifiyng structure of source code. So when saving changing something with js or by coverting to table source and adjusting js to it. Or changing js to change structure on saving file. In short it need to change html structure or maybe loop with js from elements adding some  dataset attributes and then saving in loop all values. Maybe the best way to add attributes in source like 'Name', 'Address' and etc. and then 'injecting' in xml source and saving. So adding some attributes maybe would be the most accurate way. So by according by AI. It just need to be changed structure for example: `To convert HTML to XML, you need to ensure that the content is well-formed according to XML rules. Here's what you should follow:

    Use Proper Tag Nesting: Tags must be properly opened and closed.
    No Unquoted Attribute Values: All attribute values must be enclosed in double or single quotes.
    No Special Characters: Special characters (e.g., &, <, >) must be escaped.
    No Implicit Tag Closures: All tags must explicitly close (e.g., <br /> instead of <br>).

Here’s how your provided HTML can be transformed into valid XML:

<email-address>
    <section>
        <h2 class="left hi">Email Address(es)</h2>
        <h3 class="righ" id="email">
            <a href="mailto:e-pastas@gmail.com?subject=WORK">e-pastas@gmail.com</a>
        </h3>
    </section>
</email-address>`
It just need to escape characters. What could be done with JS as well.

**Comment by KostasSliazas** [comment]
Asked AI for code and it made this: If you paste in console you can get xml right to it.
```
function generateXML() {
  // Function to create XML content from DOM element recursively
  function elementToXML(element) {
    const tagName = element.tagName.toLowerCase();
    let xmlContent = "";

    // Process only if the element has children or text content
    if (element.children.length === 0 && element.textContent.trim()) {
      xmlContent = `<${tagName}>${element.textContent.trim()}</${tagName}>`;
    } else if (element.children.length > 0) {
      xmlContent = `<${tagName}>`;
      Array.from(element.children).forEach(child => {
        xmlContent += elementToXML(child); // Recursively process child elements
      });
      xmlContent += `</${tagName}>`;
    }

    return xmlContent;
  }

  // Select the main container to start processing
  const mainContainer = document.querySelector("#main");
  if (!mainContainer) {
    console.error("Main container not found.");
    return;
  }

  // Generate XML from the main container
  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<document>`;
  Array.from(mainContainer.children).forEach(child => {
    xml += elementToXML(child);
  });
  xml += `</document>`;

  // Create a downloadable XML file
  const blob = new Blob([xml], { type: "application/xml" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "document.xml";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

 // console.log("XML Generated:\n", xml); // Log XML for debugging
}

// Trigger the function (you can bind this to a button click)
generateXML();

```

And structure would look like this: `<document>
<div>
<div>
<h1>Europass CV</h1>
</div>
<div/>
</div>
<div>
<div>
<section>
<h2>Profession Field</h2>
</section>
<section>
<h3>IT, Telecommunications, Programming, Other</h3>
</section>
</div>
<div>
<section>
<h2>Personal Information</h2>
</section>
<section>
<h2>Name / Surname</h2>
<h3>Europass Maker</h3>
</section>
<section>
<h2>Phone Number(s)</h2>
<h3>
<a>0000000000000000000</a>
</h3>
</section>
<section>
<h2>Email Address(es)</h2>
<h3>
<a>e-pastas@gmail.com</a>
</h3>
</section>
<section>
<h2>Address(es)</h2>
<h3>Address Address, Address Address (Address)</h3>
</section>
<section>
<h2>Nationality</h2>
<h3>Nationality</h3>
</section>
<section>
<h2>Date of Birth</h2>
<h3>Year Month Day</h3>
</section>
<section>
<h2>Gender</h2>
<h3>Gender</h3>
</section>
</div>
<div>
<section>
<h2>Work Experience</h2>
</section>
<div>
<section>
<h2>Dates</h2>
<h3>Date - Date</h3>
</section>
<section>
<h2>Profession or Position</h2>
<h3>CV Template Creation</h3>
</section>
<section>
<h2>Main Activities and Responsibilities</h2>
<h3>CV Template Creation</h3>
</section>
<section>
<h2>Employer Name and Address</h2>
<h3>CV Maker, Europe, Lithuania</h3>
</section>
<section>
<h2>Employer's Field of Activity or Industry Sector</h2>
<h3>Employer's Field of Activity or Industry Sector</h3>
</section>
</div>
</div>
<div>
<section>
<h2>Education</h2>
</section>
<div>
<section>
<h2>Dates</h2>
<h3>Date - Date</h3>
</section>
<section>
<h2>Qualification</h2>
<h3>Qualification</h3>
</section>
<section>
<h2>Key Subjects / Professional Skills</h2>
<h3>General Subjects - Computer Science, Foreign Language (English) Professional Subjects - Computer Hardware Setup, Maintenance, Servicing</h3>
</section>
<section>
<h2>Name and Type of Educational Provider</h2>
<h3>School Address Address, Address (Country)</h3>
</section>
<section>
<h2>Qualification Level According to National or International Classification</h2>
<h3>ISCED7</h3>
</section>
</div>
</div>
<div>
<section>
<h2>Technical Skills and Competences</h2>
</section>
<section>
<h3>CV Template Creation</h3>
</section>
</div>
<div>
<section>
<h2>Computer Skills and Competences</h2>
</section>
<section>
<h3>Operating Systems: Unix/Linux, Windows, Mac OS, Android.</h3>
</section>
</div>
<div>
<section>
<h2>Social Skills and Competences</h2>
</section>
<section>
<h3>Good communication skills; Ability to work in a team and independently</h3>
</section>
</div>
<div>
<section>
<h2>Personal Skills and Competences</h2>
</section>
<section>
<h2>Native Language(s)</h2>
<h3>Lithuanian</h3>
</section>
<section>
<h2>Other Language(s)</h2>
<h3>Language, language</h3>
</section>
<section>
<div>
<div>
<div>
<div>
<div>
<h2>Understanding</h2>
</div>
<div>
<h2>Speaking</h2>
</div>
<div>
<h2>Writing</h2>
</div>
</div>
<div>
<div>Listening</div>
<div>Reading</div>
<div>Spoken Interaction</div>
<div>Spoken Production</div>
</div>
<div>
<div>
<h3>Language</h3>
</div>
<div>Double Click</div>
<div>Double Click</div>
<div>Double Click</div>
<div>Double Click</div>
<div>Double Click</div>
</div>
<div>
<div>
<h3>Other Language</h3>
</div>
<div>Double Click</div>
<div>Double Click</div>
<div>Double Click</div>
<div>Double Click</div>
<div>Double Click</div>
</div>
</div>
</div>
</div>
</section>
</div>
</div>
</document>`

**Comment by AmauryVanEspen** [comment]
do you believe it could be compliant with the JSON Resume Schema ? https://jsonresume.org/schema

**Comment by KostasSliazas** [comment]
we just need to get values from html file and make json?: `function extractDataToJson() {
  // Extracting data from the HTML page
  const cvData = {
    basics: {
      name: document.querySelector("#vardas") ? document.querySelector("#vardas").textContent.trim() : "John Doe",
      label: document.querySelector("#pozicija") ? document.querySelector("#pozicija").textContent.trim() : "Programmer",
      image: document.querySelector("img#profile-picture") ? document.querySelector("img#profile-picture").src : "",
      email: document.querySelector("#email a") ? document.querySelector("#email a").href.replace('mailto:', '').trim() : "",
      phone: document.querySelector("#number a") ? document.querySelector("#number a").href.replace('tel:', '').trim() : "",
      url: document.querySelector("#website a") ? document.querySelector("#website a").href : "",
      summary: document.querySelector("#summary") ? document.querySelector("#summary").textContent.trim() : "No summary available",
      location: {
        address: document.querySelector("#address") ? document.querySelector("#address").textContent.trim() : "",
        postalCode: document.querySelector("#postalCode") ? document.querySelector("#postalCode").textContent.trim() : "",
        city: document.querySelector("#city") ? document.querySelector("#city").textContent.trim() : "",
        countryCode: document.querySelector("#countryCode") ? document.querySelector("#countryCode").textContent.trim() : "",
        region: document.querySelector("#region") ? document.querySelector("#region").textContent.trim() : ""
      },
      profiles: [{
        network: "Twitter",
        username: "europassmaker", // Replace with actual username if available in HTML
        url: "https://twitter.com/europassmaker" // Replace with actual URL if available
      }]
    },
    work: [{
      name: document.querySelector("#companyName") ? document.querySelector("#companyName").textContent.trim() : "Company Name",
      position: document.querySelector("#jobTitle") ? document.querySelector("#jobTitle").textContent.trim() : "Position",
      url: document.querySelector("#companyWebsite a") ? document.querySelector("#companyWebsite a").href : "",
      startDate: document.querySelector("#workStartDate") ? document.querySelector("#workStartDate").textContent.trim() : "",
      endDate: document.querySelector("#workEndDate") ? document.querySelector("#workEndDate").textContent.trim() : "",
      summary: document.querySelector("#workSummary") ? document.querySelector("#workSummary").textContent.trim() : "",
      highlights: [
        document.querySelector("#workHighlights") ? document.querySelector("#workHighlights").textContent.trim() : "No highlights available"
      ]
    }],
    volunteer: [{
      organization: "Volunteer Organization",
      position: "Volunteer Developer",
      url: "https://nonprofit.com/",
      startDate: "2019-01-01",
      endDate: "2020-01-01",
      summary: "Contributed to open-source projects.",
      highlights: [
        "Developed open-source software"
      ]
    }],
    education: [{
      institution: "University of Lithuania",
      url: "https://university.com/",
      area: "Computer Science",
      studyType: "Bachelor",
      startDate: "2015-09-01",
      endDate: "2019-06-01",
      score: "4.0",
      courses: [
        "CS101 - Introduction to Programming",
        "CS102 - Data Structures"
      ]
    }],
    awards: [{
      title: "Best Developer",
      date: "2021-06-01",
      awarder: "Company XYZ",
      summary: "Awarded for excellence in development."
    }],
    certificates: [{
      name: "Certified Web Developer",
      date: "2022-11-07",
      issuer: "Certification Body",
      url: "https://certificate.com"
    }],
    publications: [{
      name: "Creating Perfect CV Templates",
      publisher: "Tech Journal",
      releaseDate: "2022-05-01",
      url: "https://publication.com",
      summary: "A detailed guide on designing CV templates."
    }],
    skills: [{
      name: "Web Development",
      level: "Advanced",
      keywords: [
        "HTML",
        "CSS",
        "JavaScript",
        "PHP"
      ]
    }],
    languages: [{
      language: "English",
      fluency: "Native speaker"
    }],
    interests: [{
      name: "Technology",
      keywords: [
        "AI",
        "Machine Learning"
      ]
    }],
    references: [{
      name: "Jane Doe",
      reference: "John is a skilled developer who contributed significantly to our projects."
    }],
    projects: [{
      name: "CV Maker Project",
      startDate: "2019-01-01",
      endDate: "2021-01-01",
      description: "A project to create customizable CV templates.",
      highlights: [
        "Developed user-friendly templates",
        "Integrated with Europass standards"
      ],
      url: "https://cvproject.com/"
    }]
  };

  // Return the populated JSON
  return cvData;
}

// Example usage:
const jsonData = extractDataToJson();
console.log(JSON.stringify(jsonData, null, 2));
`

**Comment by KostasSliazas** [comment]
we just need to get values by id: to make it JSON: for example: `function extractDataToJson() {
  // Extracting data from the HTML page
  const cvData = {
    basics: {
      name: document.querySelector("#vardas") ? document.querySelector("#vardas").textContent.trim() : "John Doe",
      label: document.querySelector("#pozicija") ? document.querySelector("#pozicija").textContent.trim() : "Programmer",
      image: document.querySelector("img#profile-picture") ? document.querySelector("img#profile-picture").src : "",
      email: document.querySelector("#email a") ? document.querySelector("#email a").href.replace('mailto:', '').trim() : "",
      phone: document.querySelector("#number a") ? document.querySelector("#number a").href.replace('tel:', '').trim() : "",
      url: document.querySelector("#website a") ? document.querySelector("#website a").href : "",
      summary: document.querySelector("#summary") ? document.querySelector("#summary").textContent.trim() : "No summary available",
      location: {
        address: document.querySelector("#address") ? document.querySelector("#address").textContent.trim() : "",
        postalCode: document.querySelector("#postalCode") ? document.querySelector("#postalCode").textContent.trim() : "",
        city: document.querySelector("#city") ? document.querySelector("#city").textContent.trim() : "",
        countryCode: document.querySelector("#countryCode") ? document.querySelector("#countryCode").textContent.trim() : "",
        region: document.querySelector("#region") ? document.querySelector("#region").textContent.trim() : ""
      },
      profiles: [{
        network: "Twitter",
        username: "europassmaker", // Replace with actual username if available in HTML
        url: "https://twitter.com/europassmaker" // Replace with actual URL if available
      }]
    },
    work: [{
      name: document.querySelector("#companyName") ? document.querySelector("#companyName").textContent.trim() : "Company Name",
      position: document.querySelector("#jobTitle") ? document.querySelector("#jobTitle").textContent.trim() : "Position",
      url: document.querySelector("#companyWebsite a") ? document.querySelector("#companyWebsite a").href : "",
      startDate: document.querySelector("#workStartDate") ? document.querySelector("#workStartDate").textContent.trim() : "",
      endDate: document.querySelector("#workEndDate") ? document.querySelector("#workEndDate").textContent.trim() : "",
      summary: document.querySelector("#workSummary") ? document.querySelector("#workSummary").textContent.trim() : "",
      highlights: [
        document.querySelector("#workHighlights") ? document.querySelector("#workHighlights").textContent.trim() : "No highlights available"
      ]
    }],
    volunteer: [{
      organization: "Volunteer Organization",
      position: "Volunteer Developer",
      url: "https://nonprofit.com/",
      startDate: "2019-01-01",
      endDate: "2020-01-01",
      summary: "Contributed to open-source projects.",
      highlights: [
        "Developed open-source software"
      ]
    }],
    education: [{
      institution: "University of Lithuania",
      url: "https://university.com/",
      area: "Computer Science",
      studyType: "Bachelor",
      startDate: "2015-09-01",
      endDate: "2019-06-01",
      score: "4.0",
      courses: [
        "CS101 - Introduction to Programming",
        "CS102 - Data Structures"
      ]
    }],
    awards: [{
      title: "Best Developer",
      date: "2021-06-01",
      awarder: "Company XYZ",
      summary: "Awarded for excellence in development."
    }],
    certificates: [{
      name: "Certified Web Developer",
      date: "2022-11-07",
      issuer: "Certification Body",
      url: "https://certificate.com"
    }],
    publications: [{
      name: "Creating Perfect CV Templates",
      publisher: "Tech Journal",
      releaseDate: "2022-05-01",
      url: "https://publication.com",
      summary: "A detailed guide on designing CV templates."
    }],
    skills: [{
      name: "Web Development",
      level: "Advanced",
      keywords: [
        "HTML",
        "CSS",
        "JavaScript",
        "PHP"
      ]
    }],
    languages: [{
      language: "English",
      fluency: "Native speaker"
    }],
    interests: [{
      name: "Technology",
      keywords: [
        "AI",
        "Machine Learning"
      ]
    }],
    references: [{
      name: "Jane Doe",
      reference: "John is a skilled developer who contributed significantly to our projects."
    }],
    projects: [{
      name: "CV Maker Project",
      startDate: "2019-01-01",
      endDate: "2021-01-01",
      description: "A project to create customizable CV templates.",
      highlights: [
        "Developed user-friendly templates",
        "Integrated with Europass standards"
      ],
      url: "https://cvproject.com/"
    }]
  };

  // Return the populated JSON
  return cvData;
}

// Example usage:
const jsonData = extractDataToJson();
console.log(JSON.stringify(jsonData, null, 2));
`

**Comment by AmauryVanEspen** [comment]
is this a GPT generated answer or is it a running code ?

**Comment by KostasSliazas** [comment]
yes, its example how can make like JSON file extracting values from HTML.

**Comment by AmauryVanEspen** [comment]
OK,
i was a bit confused, because, the function does not run properly =)

**Comment by KostasSliazas** [comment]
Yes, it need to be adjusted by JSON keys. I have modified it for work experience.

**Comment by KostasSliazas** [comment]
```

const jsonData = {
    "basics": {},
    "work": [],
    "volunteer": [],
    "education": [],
    "awards": [],
    "certificates": [],
    "publications": [],
    "skills": [],
    "languages": [],
    "interests": [],
    "references": [],
    "projects": []
  };

  // Function to extract basic information (personal info)  >>>>>>>>>>>>>>>>>>>>>>>basics<<<<<<<<<<<<<<<<<<<<<<<
  function extractBasics() {
    const label = document?.getElementById('label')?.textContent.trim() || null;
    const name = document?.getElementById('name')?.textContent.trim() || null;
    const email = document?.getElementById('email')?.getElementsByTagName('a')[0]?.textContent.replace(/\s+/g, '') || null;
    const phone = document?.getElementById('number')?.getElementsByTagName('a')[0]?.textContent.replace(/\s+/g, '') || null;
    const address = document?.getElementById('address')?.textContent.trim() || null;
    const image = document?.getElementById('preview')?.src || null;
    const url = document?.getElementById('url').getElementsByTagName('a')[0]?.href.trim() || null;
    const postalCode = document?.getElementById('postal-code')?.textContent.trim() || null;
    const city = document?.getElementById('city')?.textContent.trim() || null;
    const countryCode = document?.getElementById('country-code')?.textContent.trim() || null;
    const region = document?.getElementById('region')?.textContent.trim() || null;
    const summary = document?.getElementById('summary')?.textContent.trim() || null;
    // Only add the fields if they exist
    if (name) jsonData.basics.name = name;
    if (label) jsonData.basics.label = label;
    if (image) jsonData.basics.image = image;
    if (email) jsonData.basics.email = email;
    if (phone) jsonData.basics.phone = phone;
    if (url) jsonData.basics.url = url;
    if (summary) jsonData.basics.summary = summary;

    if (address || city) {
      jsonData.basics.location = {};
      if (address) jsonData.basics.location.address = address;
      if (postalCode) jsonData.basics.location.postalCode = postalCode;
      if (city) jsonData.basics.location.city = city;
      if (countryCode) jsonData.basics.location.countryCode = countryCode;
      if (region) jsonData.basics.location.region = region;
    }
  }
  // Function to extract WORK experience  >>>>>>>>>>>>>>>>>>>>>>>work<<<<<<<<<<<<<<<<<<<<<<<
  function extractWorkExperience() {

    const workElements = [...document.getElementsByClassName('experience')];

    workElements.forEach((work) => {
      let workExperience = {};

      const dateStart = work?.getElementsByTagName('h3')[0]?.textContent.trim() || null;
      const dateEnd = work?.getElementsByTagName('h3')[1]?.textContent.trim() || null;
      const position = work?.getElementsByTagName('h3')[2]?.textContent.trim() || null;
      const name = work?.getElementsByTagName('h3')[4]?.textContent.trim() || null;
      const highlights = work?.getElementsByTagName('h3')[5]?.textContent.trim() || null;
      const summary = work?.getElementsByTagName('h3')[3]?.textContent.trim() || null;
      const url = work?.getElementsByTagName('h3')[6]?.getElementsByTagName('a')[0]?.href || null;

      // Only add fields if they exist
      if (name) workExperience.name = name;
      if (position) workExperience.position = position;
      if (url) workExperience.url = url;
      if (dateStart) workExperience.startDate = dateStart;
      if (dateEnd) workExperience.endDate = dateEnd;
      if (summary) workExperience.summary = summary;
      if (highlights) workExperience.highlights = [highlights];

      if (Object.keys(workExperience).length > 0) {
        jsonData.work.push(workExperience);
      }
    });
  }

  // Function to extract education information >>>>>>>>>>>>>>>>>>>>>>>education<<<<<<<<<<<<<<<<<<<<<<<
  function extractEducation() {
    const educationSections = [...document.getElementsByClassName('education')];

    educationSections.forEach((eduSection) => {
      let education = {};

      const dateStart = eduSection?.getElementsByTagName('h3')[0]?.textContent.trim() || null;
      const dateEnd = eduSection?.getElementsByTagName('h3')[1]?.textContent.trim() || null;
      const studyType = eduSection?.getElementsByTagName('h3')[2]?.textContent.trim() || null;
      const area = eduSection?.getElementsByTagName('h3')[3]?.textContent.trim() || null;
      const institution = eduSection?.getElementsByTagName('h3')[4]?.textContent.trim() || null;
      const score = eduSection?.getElementsByTagName('h3')[5]?.textContent.trim() || null;
      const url = eduSection?.getElementsByTagName('h3')[6]?.getElementsByTagName('a')[0]?.href || null;

      // Only add fields if they exist
      if (institution) education.institution = institution;
      if (url) education.url = url;
      if (area) education.area = area;
      if (studyType) education.studyType = studyType;
      if (dateStart) education.startDate = dateStart;
      if (dateEnd) education.endDate = dateEnd;
      if (score) education.score = score;

      if (Object.keys(education).length > 0) {
        jsonData.education.push(education);
      }
    });
  }

  function extractSkills() {
    const skillElements = [...document.getElementsByClassName('skills')];

    skillElements.forEach((skill) => {
      let skillData = {};

      // Extracting level, keywords, and name based on your HTML structure
      const level = skill?.getElementsByClassName('righ')[0]?.textContent.trim() || null;
      const keywordsInput = skill?.getElementsByClassName('righ')[1]?.textContent.trim() || null;
      const name = skill?.getElementsByClassName('left')[0]?.textContent.trim() || null;

      // Convert keywords into an array (comma-separated values)
      const keywordsArray = keywordsInput ? keywordsInput.split(',').map(keyword => keyword.trim()) : [];

      // Only add fields if they exist
      if (name) skillData.name = name;
      if (level) skillData.level = level;
      if (keywordsArray.length > 0) skillData.keywords = keywordsArray;

      if (Object.keys(skillData).length > 0) {
        // Push the extracted skill data into your JSON object or array
        jsonData.skills.push(skillData);
      }
    });
  }

  function extractLanguages() {
    const languageElements = [...document.querySelectorAll('.languages section')];

    languageElements.forEach((lang) => {
      let languageData = {};

      // Extract language name (left side)
      const language = lang.querySelector('.left')?.textContent.trim() || null;

      // Extract fluency level (right side)
      const fluency = lang.querySelector('.righ')?.textContent.trim() || null;

      // Only add fields if they exist
      if (language) languageData.language = language;
      if (fluency) languageData.fluency = fluency;

      // If valid data, push it to the languages array
      if (Object.keys(languageData).length > 0) {
        jsonData.languages.push(languageData);
      }
    });
  }

  function generateDate() {
    const date = new Date(); // Get the current date
    const year = date.getFullYear(); // Get the full year (4 digits)
    const month = String(date.getMonth() + 1).padStart(2, '0'); // Get the month (0-based, so add 1 and pad to 2 digits)
    const day = String(date.getDate()).padStart(2, '0'); // Get the day of the month and pad to 2 digits
    return `${year}-${month}-${day}`; // Return the formatted date
  }

    extractLanguages();
    extractSkills()
    extractBasics();
    extractWorkExperience();
    extractEducation();

  function exportToJson(data, fileName = 'data.json') {
    // Convert the data object to a JSON string
    const jsonString = JSON.stringify(data, null, 2);

    // Create a Blob with the JSON data
    const blob = new Blob([jsonString], {
      type: 'application/json'
    });

    // Create a download link
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = fileName;

    // Trigger the download
    link.click();

    // Clean up
    URL.revokeObjectURL(link.href);
  }
  exportToJson(jsonData, 'data.json');

```

**Comment by KostasSliazas** [comment]
hello, sorry I'm not familiar with these tools , what it does it change some schema values, and when you paste raw data [editor](https://registry.jsonresume.org/editor ) it will show some basic info. I have added whole schema and it will print all in editor. And when you have *.json data you can insert or edit and insert somewhere and have standard data.And as I understand then we can use *.html templates and export to *.pdf with tools. There is tutorial [tutorial](https://youtu.be/BxpHgNM0clE ) probably would say more with examples.
